# Generated by Django 5.1.1 on 2024-09-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom Users', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
