# Generated by Django 5.1.1 on 2024-09-22 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'guide'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('travel_places', models.ManyToManyField(related_name='guides', to='app.travelplace')),
            ],
        ),
        migrations.CreateModel(
            name='BookGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_location', models.CharField(max_length=255)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('guide', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'guide'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_guide', to=settings.AUTH_USER_MODEL)),
                ('travel_user', models.ForeignKey(limit_choices_to={'user_type': 'travel_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings_as_travel_user', to=settings.AUTH_USER_MODEL)),
                ('travel_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.travelplace')),
            ],
        ),
        migrations.CreateModel(
            name='TravelUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'travel_user'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
