# Generated by Django 5.1.1 on 2024-09-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookguide',
            old_name='guide',
            new_name='guide_user',
        ),
    ]
