# Generated by Django 5.1.1 on 2024-09-29 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookguide_canceled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('guide_user', models.ForeignKey(limit_choices_to={'user_type': 'guide'}, on_delete=django.db.models.deletion.PROTECT, related_name='reported_as_guide_user', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(limit_choices_to={'user_type': 'travel_user'}, on_delete=django.db.models.deletion.PROTECT, related_name='reported_as_travel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
